FV/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manga/', include('mangalib.urls')) 
]

mangalib/urls.py
from django.urls import path
from . import views

app_name = "mangalib"

urlpatterns = [
    path('', views.index, name='index'), # manga/
    path('<int:book_id>/', views.show, name='show'), # manga/<id>
    path('Ajouter-livre/', views.add, name = 'add'),
    path('modifier-livre/<int:book_id>/', views.edit, name = 'edit'),
    path('Supprimer-livre/<int:book_id>/', views.remove, name='delete')
]

mangalib/models.py
from django.db import models

class Author(models.Model):
    name = models.CharField(max_length = 64, unique=True,
    verbose_name= "Nom") 
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Auteur"
        verbose_name_plural = "Auteurs"

class Book(models.Model):
    title = models.CharField(max_length = 32, unique=True, verbose_name="Titre")
    quantity = models.IntegerField(default = 1, verbose_name="Quantité")
    author = models.ForeignKey(Author, on_delete= models.DO_NOTHING, verbose_name="Auteur")  

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Livre"
        verbose_name_plural = "Livres"
                                       

mangalib/forms.py
from django import forms
from .models import Author, Book

class BookForm(forms.ModelForm):
    author = forms.ModelChoiceField(queryset = Author.objects.all(), label = "Autheur")

    class Meta:
        model = Book
        fields = ['title', 'author','quantity']
        labels = {'title': 'Titre', 'quantity': 'Quantité' }

mangalib/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Book, Author
from .forms import BookForm

def index(request):
    context = { "books": Book.objects.all()}
    return render(request, "mangalib/index.html", context)
    

def show(request, book_id):
    
    context = {"book" : get_object_or_404(Book, pk = book_id)}
    return render(request, "mangalib/show.html", context) 

def add(request):
    if request.method == 'POST':
        form = BookForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("mangalib:index")
    else:
        form = BookForm()

    return render(request, "mangalib/book-form.html", {"form": form})
    

def edit(request, book_id):

    book = Book.objects.get(pk = book_id)

    if request.method == 'POST':
        form = BookForm(request.POST, instance= book)

        if form.is_valid():
            form.save()
            return redirect("mangalib:index")
    else:
        form = BookForm(instance= book)

    return render(request, "mangalib/book-form.html", {"form": form})

def remove(request, book_id):
    book = Book.objects.get(pk = book_id)
    book.delete()

    return redirect("mangalib:index")

mangalib/templates/mangalib/book-form.html
{% include 'mangalib/include/begin_page.html'%}

<h1>Gestion du livre</h1>

<form method="post">
    {% csrf_token %} 
    {{ form.as_p}} 
    <input type="submit" value="Ajouter">
</form>

{% include 'mangalib/include/end_page.html' %}

mangalib/templates/mangalib/include/begin_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mes mangas</title>
    <link rel="stylesheet" href="{%static 'mangalib/css/main.css' %}">
</head>
<body>

mangalib/templates/mangalib/include/end_page.html
</body>
</html>

mangalib/templates/mangalib/index.html
{% include 'mangalib/include/begin_page.html'%}


<h1>Bienvenue sur Mangalib !</h1>
<p><a href="{% url 'mangalib:add' %}">+ AJOUTER LIVRE</a></p>

<table>
    <tr>
        <th>Nom</th>
        <th>AUTEUR</th>
        <th>QTE</th>
        <th colspan="2">ACTIONS</th>
    </tr>
    {% for book in books %}

    <tr>
        <td><a href="{% url 'mangalib:show' book.id %}">{{ book.title }}</a></td>
        <td>{{ book.author }}</td>
        <td>{{ book.quantity }}</td>
        <td><a href="{% url 'mangalib:edit' book.id %}">/</a></td>
        <td><a href="{% url 'mangalib:delete' book.id %}">X</a></td>
    </tr>
    {% endfor %}
</table>
<br>

{% include 'mangalib/include/end_page.html' %}

mangalib/templates/mangalib/show.html
{% include 'mangalib/include/begin_page.html'%}

    <h1 >{{ book.title }}</h1>
   
    <p> Quantité : {{ book.quantity}}</p>
    <p> Auteur : {{ book.author.name }}</p>
    <p><a href="{% url 'mangalib:index' %}">&laquo; Revenir à la liste des livres</a></p>


    {% include 'mangalib/include/end_page.html' %}